/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 2830482321039
 */
public class Calculadora extends javax.swing.JFrame {

    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
            initComponents();
        }
        double valor1, valor2;
        String operacao;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtResultado = new javax.swing.JTextField();
        botaoBackspace = new javax.swing.JButton();
        botaoC = new javax.swing.JButton();
        botaoCE = new javax.swing.JButton();
        botao7 = new javax.swing.JButton();
        botao8 = new javax.swing.JButton();
        botao9 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        botaoSoma = new javax.swing.JButton();
        botaoMultiplicacao = new javax.swing.JButton();
        botaoSub = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        botaoDividir = new javax.swing.JButton();
        botao0 = new javax.swing.JButton();
        botaoPonto = new javax.swing.JButton();
        botaoIgual = new javax.swing.JButton();
        lblValor1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResultadoActionPerformed(evt);
            }
        });

        botaoBackspace.setText("<-");
        botaoBackspace.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        botaoBackspace.setMargin(new java.awt.Insets(26, 26, 26, 26));

        botaoC.setText("C");
        botaoC.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        botaoC.setMargin(new java.awt.Insets(26, 26, 26, 26));
        botaoC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCActionPerformed(evt);
            }
        });

        botaoCE.setText("CE");
        botaoCE.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        botaoCE.setMargin(new java.awt.Insets(26, 26, 26, 26));

        botao7.setText("7");
        botao7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        botao7.setMargin(new java.awt.Insets(26, 26, 26, 26));
        botao7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao7(evt);
            }
        });

        botao8.setText("8");
        botao8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        botao8.setMargin(new java.awt.Insets(26, 26, 26, 26));
        botao8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao8(evt);
            }
        });

        botao9.setText("9");
        botao9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        botao9.setMargin(new java.awt.Insets(26, 26, 26, 26));
        botao9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao9(evt);
            }
        });

        jButton8.setText("4");
        jButton8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jButton8.setMargin(new java.awt.Insets(26, 26, 26, 26));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao4(evt);
            }
        });

        jButton9.setText("5");
        jButton9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jButton9.setMargin(new java.awt.Insets(26, 26, 26, 26));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao5(evt);
            }
        });

        jButton10.setText("6");
        jButton10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jButton10.setMargin(new java.awt.Insets(26, 26, 26, 26));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao6(evt);
            }
        });

        jButton11.setText("1");
        jButton11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jButton11.setMargin(new java.awt.Insets(26, 26, 26, 26));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        botaoSoma.setText("+");
        botaoSoma.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        botaoSoma.setMargin(new java.awt.Insets(26, 26, 26, 26));
        botaoSoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSoma(evt);
            }
        });

        botaoMultiplicacao.setText("*");
        botaoMultiplicacao.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        botaoMultiplicacao.setMargin(new java.awt.Insets(26, 26, 26, 26));
        botaoMultiplicacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMultiplicacaoActionPerformed(evt);
            }
        });

        botaoSub.setText("-");
        botaoSub.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        botaoSub.setMargin(new java.awt.Insets(26, 26, 26, 26));
        botaoSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSubActionPerformed(evt);
            }
        });

        jButton16.setText("2");
        jButton16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jButton16.setMargin(new java.awt.Insets(26, 26, 26, 26));
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jButton17.setText("3");
        jButton17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jButton17.setMargin(new java.awt.Insets(26, 26, 26, 26));
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        botaoDividir.setText("/");
        botaoDividir.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        botaoDividir.setMargin(new java.awt.Insets(26, 26, 26, 26));
        botaoDividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoDividirActionPerformed(evt);
            }
        });

        botao0.setText("0");
        botao0.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        botao0.setMargin(new java.awt.Insets(26, 26, 26, 26));
        botao0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao0ActionPerformed(evt);
            }
        });

        botaoPonto.setText(".");
        botaoPonto.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        botaoPonto.setMargin(new java.awt.Insets(26, 26, 26, 26));
        botaoPonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPontoActionPerformed(evt);
            }
        });

        botaoIgual.setText("=");
        botaoIgual.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        botaoIgual.setMargin(new java.awt.Insets(26, 26, 26, 26));
        botaoIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoIgual(evt);
            }
        });

        lblValor1.setText("lblValor1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblValor1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtResultado, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(botaoCE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(botaoC)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(botaoBackspace))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(botao7)
                                    .addComponent(jButton8))
                                .addComponent(jButton11))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(botao8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(botao9))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButton9)
                                        .addComponent(jButton16)
                                        .addComponent(botao0))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButton17)
                                        .addComponent(jButton10)
                                        .addComponent(botaoPonto))))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(botaoSoma)
                                .addComponent(botaoMultiplicacao)
                                .addComponent(botaoSub)
                                .addComponent(botaoDividir)
                                .addComponent(botaoIgual)))))
                .addGap(0, 16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblValor1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoBackspace)
                    .addComponent(botaoC)
                    .addComponent(botaoCE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoSoma)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botao7)
                    .addComponent(botao8)
                    .addComponent(botao9)
                    .addComponent(botaoMultiplicacao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8)
                    .addComponent(jButton9)
                    .addComponent(jButton10)
                    .addComponent(botaoSub))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton11)
                    .addComponent(jButton16)
                    .addComponent(jButton17)
                    .addComponent(botaoDividir))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botao0)
                            .addComponent(botaoPonto)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(botaoIgual)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botao7(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao7
        txtResultado.setText(txtResultado.getText()+"7");
    }//GEN-LAST:event_botao7

    private void botao8(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao8
        txtResultado.setText(txtResultado.getText()+"8");
    }//GEN-LAST:event_botao8

    private void botao9(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao9
        txtResultado.setText(txtResultado.getText()+"9");
    }//GEN-LAST:event_botao9

    private void botao4(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao4
        txtResultado.setText(txtResultado.getText()+"4");
    }//GEN-LAST:event_botao4

    private void botao5(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao5
        txtResultado.setText(txtResultado.getText()+"5");
    }//GEN-LAST:event_botao5

    private void botao6(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao6
        txtResultado.setText(txtResultado.getText()+"6");
    }//GEN-LAST:event_botao6

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        txtResultado.setText(txtResultado.getText()+"1");
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        txtResultado.setText(txtResultado.getText()+"2");
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        txtResultado.setText(txtResultado.getText()+"3");
    }//GEN-LAST:event_jButton17ActionPerformed

    private void botao0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao0ActionPerformed
        txtResultado.setText(txtResultado.getText()+"0");
    }//GEN-LAST:event_botao0ActionPerformed

    private void botaoPontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPontoActionPerformed
        txtResultado.setText(txtResultado.getText()+".");
    }//GEN-LAST:event_botaoPontoActionPerformed

    private void botaoSoma(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSoma
        lblValor1.setText(txtResultado.getText());
        txtResultado.setText("");    
        
        valor1 = Double.parseDouble(lblValor1.getText());
        operacao = "soma";
    }//GEN-LAST:event_botaoSoma

    private void txtResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResultadoActionPerformed
        txtResultado.setText(txtResultado.getText()+"0"); 
    }//GEN-LAST:event_txtResultadoActionPerformed

    private void botaoIgual(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoIgual
            double resultado;
            valor2 = Double.parseDouble(txtResultado.getText());
            switch(operacao){
                case "soma":
                    resultado = valor1 + valor2;
                    lblValor1.setText(valor1+"+"+valor2+"=");
                    txtResultado.setText(String.valueOf(resultado));
                    break;
                case "subtrair":
                    resultado = valor1 - valor2;
                    lblValor1.setText(valor1+"-"+valor2+"=");
                    txtResultado.setText(String.valueOf(resultado));
                    break;
                case "multiplicacao":
                    resultado = valor1 * valor2;
                    lblValor1.setText(valor1+"*"+valor2+"=");
                    txtResultado.setText(String.valueOf(resultado));
                    break;
                case "divisao":
                    resultado = valor1 / valor2;
                    lblValor1.setText(valor1+"/"+valor2+"=");
                    txtResultado.setText(String.valueOf(resultado));
                    break;
                default:
                    txtResultado.setText("Operacao invalida :/");
                    break;
            }
    }//GEN-LAST:event_botaoIgual

    private void botaoSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSubActionPerformed
        lblValor1.setText(txtResultado.getText());
        txtResultado.setText("");    
        
        valor1 = Double.parseDouble(lblValor1.getText());
        operacao = "subtrair";
    }//GEN-LAST:event_botaoSubActionPerformed

    private void botaoMultiplicacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMultiplicacaoActionPerformed
        lblValor1.setText(txtResultado.getText());
        txtResultado.setText("");    
        
        valor1 = Double.parseDouble(lblValor1.getText());
        operacao = "multiplicacao";
    }//GEN-LAST:event_botaoMultiplicacaoActionPerformed

    private void botaoDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoDividirActionPerformed
        lblValor1.setText(txtResultado.getText());
        txtResultado.setText("");    
        
        valor1 = Double.parseDouble(lblValor1.getText());
        operacao = "divisao";
    }//GEN-LAST:event_botaoDividirActionPerformed

    private void botaoCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCActionPerformed
       txtResultado.setText("");
    }//GEN-LAST:event_botaoCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao0;
    private javax.swing.JButton botao7;
    private javax.swing.JButton botao8;
    private javax.swing.JButton botao9;
    private javax.swing.JButton botaoBackspace;
    private javax.swing.JButton botaoC;
    private javax.swing.JButton botaoCE;
    private javax.swing.JButton botaoDividir;
    private javax.swing.JButton botaoIgual;
    private javax.swing.JButton botaoMultiplicacao;
    private javax.swing.JButton botaoPonto;
    private javax.swing.JButton botaoSoma;
    private javax.swing.JButton botaoSub;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel lblValor1;
    private javax.swing.JTextField txtResultado;
    // End of variables declaration//GEN-END:variables
}
